[package]
name = "read_json_from_file"
version = "0.1.0"
authors = ["Tonatiuh Martinez <merodeador.nocturno@gmail.com>"]
edition = "2018"

[dependencies]
serde = "*"
serde_json = "*"
serde_derive = "*"

[profile.dev]
opt-level = 3
